### PR TITLE
fix for tile objects with empty name

### PR DESCRIPTION
**Pull request by terebentina**

### CODE REVIEW

**Comment by terebentina** [comment]
From chat with @parasyte :
parasyte an hour ago 
"TileObject" is set here: https://github.com/melonjs/melonJS/blob/v2.0.2/src/level/TMXObjectGroup.js#L333
And defined in the pool here: https://github.com/melonjs/melonJS/blob/v2.0.2/src/system/pooling.js#L43
This is what I meant by "hardcoded"
Tile Object with no name -> creates a Sprite.
terebentina 16 minutes ago 
aha!!!!
had to debug melon step by step but I found the problem
TileObject is indeed set here https://github.com/melonjs/melonJS/blob/v2.0.2/src/level/TMXObjectGroup.js#L333
IF the name is undefined
however, it's not undefined, it's the empty string
at least in tiled 0.11

**Comment by parasyte** [comment]
@obiot @agmcleod We might actually want do a 2.0.3 release? This patch and maybe one for the floating container bug #649 would be a nice for the 2.0.x folks, even with the next release coming soon...

What do you think?

**Comment by obiot** [comment]
Hmmm... I would say: 
Is there any easy workaround to those two issues? If yes i would not do it as we are on the verge anyway to release 2.1.0

**Comment by obiot** [comment]
Not sure though that the fix is correct on 2.0.2, as this would probably set the name of the collision shapes also to "TileObject" (would work though)

**Comment by parasyte** [comment]
@obiot With all the bugs we are fixing (and still finding) I don't think 2.1 is nearly ready for RC.

**Comment by obiot** [comment]
indeed, we have more & more issues popping up :(

**Comment by obiot** [comment]
2.1.0 being there now, closing this one :P

**Pull request closed without merging**
