### PR TITLE
Update font.js

### PR DESCRIPTION
**Pull request by zoiba**
I've modified the _drawFont function for handling the stroke parameter

### CODE REVIEW

**Comment by parasyte** [comment]
@zoiba This PR fails lint because we have strict whitespace rules: https://travis-ci.org/melonjs/melonJS/builds/64806648

**Comment by zoiba** [comment]
sorry, forgot the space between "}" and "else".

**Comment by parasyte** [comment]
Thanks!

**Comment by obiot** [comment]
This one could also be merged in the 2.1.x branch as it does not change any api ?

**Comment by zoiba** [comment]
yes please. I'm already using it in a modified 2.1.1 version because I need the font.drawStroke function.

**Comment by obiot** [comment]
@parasyte would you mind doing your magic with `git-cherrypick` i'm afraid to do something bad again, as I'm used to sometimes :):):)

**Comment by agmcleod** [comment]
@obiot done.

**Comment by parasyte** [comment]
@agmcleod You missed the followup commits. :wink: I got it...

**Comment by agmcleod** [comment]
aw lol. i tried :D

**Pull request merged**
