### PR TITLE
[#872] Add touchstart to pointer event check

### PR DESCRIPTION
**Pull request by Ld00d**
Just adding the 4th element of the POINTER_DOWN array to the check for bound pointer events.

### CODE REVIEW

**Comment by obiot** [comment]
good catch ! i cannot even believe nobody saw this before, I guess this is another regression following the small refactoring in 4.0.0.

maybe we can shorten the code though by using a 
```` javascript
if (POINTER_DOWN.indexOf(e.type) === -1) {
   ....
}
```

thank you very much, if you could just do this last change, and then we can merge it :)

**Comment by parasyte** [comment]
```javascript
if (POINTER_DOWN.indexof(e.type) >= 0) { /* ... */ }
```

But yeah, for sure, I also think this patch is needed.

**Comment by Ld00d** [comment]
I considered indexOf, but I thought maybe it was a performance concern. I'll make the change...

**Comment by parasyte** [comment]
`indexOf` will probably be faster, because the iteration can be done in native code. Checking each index of an array in JavaScript is just an unrolled iteration loop. ;)

**Pull request merged**
