### PR TITLE
Implemented me.TMXHexagonalRenderer

### PR DESCRIPTION
**Pull request by matthewmmorrow**
I started using melonjs because I saw Tiled had support for hex maps. Sat down to start my game and realized melonjs didn't! Well, now hopefully it will.

Implemented the tmx hexagonal rendering using the math from Tiled's same
renderer. Added an example which displays a hexagonal map and a tile's
index when moused over to show pixel to tile math.

Let me know if I'm missing anything, this is my first real open source pull request.

### CODE REVIEW

**Comment by ldd** [comment]
This is awesome (random melonJS user here, just saying)

**Comment by matthewmmorrow** [comment]
This will likely close https://github.com/melonjs/melonJS/issues/607

**Comment by obiot** [comment]
this is amazing ! I meant to finish this one as part of the 2.1.x branch, but got sidetracked by other topics ,and did not have the time to finish it (beyond that basic skeleton I added).

I'll merge it right away (seems like there are some small space issues, but weirdly the travis build status is ok)

**Comment by obiot** [comment]
i did a few changes, cleaned up the spaces issues, and most of all some changes to prevent unnecessary object allocation, should be faster as well :P

**Comment by obiot** [comment]
and thank you again for your contribution :P

**Comment by bjorn** [comment]
:+1: Nice!

**Pull request merged**
