### PR TITLE
Option to use getBoundingClientRect() for parent dimensions

### PR DESCRIPTION
**Pull request by krojew**
fix for #801

### CODE REVIEW

**Comment by krojew** [comment]
Any chance for this being merged?

**Comment by obiot** [comment]
my apologies, with the holiday season I took a small needed break as well from melonJS :)

looks good to me, the only thing would be to find a short name for `useParentBoundingClientRect` ? but I have no idea right now :)

@parasyte @agmcleod any feedback ?

**Comment by obiot** [comment]
i still have another bug i need to fix before releasing a 4.1.0 version, so we still have few days to finalise this one :)

**Comment by krojew** [comment]
Cool. BTW. can you take a look at https://github.com/melonjs/melonJS/pull/806#issuecomment-268463270 and tell me what you think?

**Comment by obiot** [comment]
shorter proposition :
````javascript
* @param {Boolean} [options.useParentDOMSize=false] on browser devices, limit the canvas width and height to its parent container dimensions as returned by getBoundingClientRect(), as opposed to the browser window dimensions
````

**Comment by obiot** [comment]
ok cool, let's merge it then ! thank you again @krojew

**Pull request merged**
