### PR TITLE
Made loader reentrant

### PR DESCRIPTION
**Pull request by krojew**
ticket #844

### CODE REVIEW

**Comment by obiot** [comment]
I'm not sure to get how it fixes it, but happy to merge it if it does :) thanks for the PR!

**Comment by parasyte** [comment]
I'm confused by it, too. Does the bug occur as a result of dereferencing the `onload` method after the timeout fires? And caching the method at timer-creation resolves some race condition? Even then, still not clear how this prevents it from a double-call.

**Comment by krojew** [comment]
This doesn't prevent a double call, rather calls the proper callback. Consider the situation:

1. Call preload and pass a callback.
1. Call preload again and pass other callback.
1. Both loads finish and the second callback is called twice.

The reason is mixing async callbacks with the lack of reentrancy - this sooner or later had to result in an error. I suggest looking at other places where some global state is being used along with async calls.

**Comment by parasyte** [comment]
Oh, you are calling `loader.preload()` more than once. Understood. These changes for #844 are :+1:

**Pull request merged**
