### PR TITLE
Add typescript declaration file

### PR DESCRIPTION
**Pull request by qpwo**
Typescript can generate .d.ts files from jsdoc comments. Just a handful of small patches to the source comments were needed. Seems to work. Will post example repo in a sec.

### CODE REVIEW

**Comment by qpwo** [comment]
Ok here's the start of a template repo. Not complete yet. And there may be a few more bugs to work out with the declaration file from melon. I think I'm out of time today but curious as to your thoughts on this.

https://github1s.com/qpwo/melonjs-typescript-boilerplate

https://github.com/qpwo/melonjs-typescript-boilerplate

**Comment by obiot** [comment]
awesome I wanted to look at it as well, it's even easier than what I though ! thank you !

Just one thing, this pull request is against the master branch which is the latest with the full es6 implementation and no API backward compatibility (all deprecated methods have been removed). Just to be sure this what you are looking for. And also this 10.0.0 version is not yet on NPM (I'm still debugging/testing it for regression).

Legacy "melonJS 1" version is now on the legacy branch here : https://github.com/melonjs/melonJS/tree/legacy

**Comment by obiot** [comment]
pull request merged, I will do a couple of small fixes, including changing back the package name to `melonjs` in package.json

**Comment by obiot** [comment]
just realized it actually breaks the jsdoc generation 

````
ERROR: Unable to parse a tag's type expression for source file /Users/obiot/Documents/GitHub/melonJS/src/audio/audio.js in line 63 with tag title "type" and text "{(audioFormat: string) => boolean}": Invalid type expression "(audioFormat: string) => boolean": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter, or [1-9] but " " found.
ERROR: Unable to parse a tag's type expression for source file /Users/obiot/Documents/GitHub/melonJS/src/audio/audio.js in line 86 with tag title "type" and text "{(audioFormat: string) => boolean}": Invalid type expression "(audioFormat: string) => boolean": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter, or [1-9] but " " found.
ERROR: Unable to parse a tag's type expression for source file /Users/obiot/Documents/GitHub/melonJS/src/game.js in line 96 with tag title "type" and text "{() => void}": Invalid type expression "() => void": Expected "!", "=", "?", or end of input but " " found.
ERROR: Unable to parse a tag's type expression for source file /Users/obiot/Documents/GitHub/melonJS/src/game.js in line 104 with tag title "type" and text "{() => void}": Invalid type expression "() => void": Expected "!", "=", "?", or end of input but " " found.
ERROR: Unable to parse a tag's type expression for source file /Users/obiot/Documents/GitHub/melonJS/src/game.js in line 115 with tag title "type" and text "{() => void}": Invalid type expression "() => void": Expected "!", "=", "?", or end of input but " " found.
ERROR: Unable to parse a tag's type expression for source file /Users/obiot/Documents/GitHub/melonJS/src/game.js in line 124 with tag title "type" and text "{() => void}": Invalid type expression "() => void": Expected "!", "=", "?", or end of input but " " found.
ERROR: Unable to parse a tag's type expression for source file /Users/obiot/Documents/GitHub/melonJS/src/tweens/tween.js in line 77 with tag title "type" and text "{(o: Record<string, unknown>) => void}": Invalid type expression "(o: Record<string, unknown>) => void": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter, or [1-9] but " " found.
ERROR: Unable to parse a tag's type expression for source file /Users/obiot/Documents/GitHub/melonJS/src/tweens/tween.js in line 81 with tag title "type" and text "{(o: Record<string, unknown>) => void}": Invalid type expression "(o: Record<string, unknown>) => void": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter, or [1-9] but " " found.
ERROR: Unable to parse a tag's type expression for source file /Users/obiot/Documents/GitHub/melonJS/src/video/video.js in line 100 with tag title "type" and text "{(game_width: number, game_height: number, options: {     parent: String|HTMLElement     renderer: Number     doubleBuffering: Boolean     scale: Number|String     scaleMethod: String     preferWebGL1: Boolean     powerPreference: String     transparent: Boolean}) => boolean}": Invalid type expression "(game_width: number, game_height: number, options: {     parent: String|HTMLElement     renderer: Number     doubleBuffering: Boolean     scale: Number|String     scaleMethod: String     preferWebGL1: Boolean     powerPreference: String     transparent: Boolean}) => boolean": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter, or [1-9] but " " found.
ERROR: Unable to parse a tag's type expression for source file /Users/obiot/Documents/GitHub/melonJS/src/video/video.js in line 156 with tag title "type" and text "{(game_width: number, game_height: number, options: {     parent: String|HTMLElement     renderer: Number     doubleBuffering: Boolean     scale: Number|String     scaleMethod: String     preferWebGL1: Boolean     powerPreference: String     transparent: Boolean}) => boolean}": Invalid type expression "(game_width: number, game_height: number, options: {     parent: String|HTMLElement     renderer: Number     doubleBuffering: Boolean     scale: Number|String     scaleMethod: String     preferWebGL1: Boolean     powerPreference: String     transparent: Boolean}) => boolean": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter, or [1-9] but " " found.
````

**Comment by qpwo** [comment]
Oh crap sorry about that didn't think to check jsdoc. Can investigate in morning

**Comment by qpwo** [comment]
Oh and yes was using this version on purpose since typescript didn't like using ‘.extends`

**Pull request merged**
