### PR TITLE
Updated platformer example so that it exposes the parallax bug.

### PR DESCRIPTION
**Pull request by Giwayume**

### CODE REVIEW

**Comment by Giwayume** [comment]
As far as the bug goes, the anchor point is arriving to the code as a string "{"x":0.5,"y":0.5}", not a json object.

**Comment by parasyte** [comment]
Use `json:{"x":0.5,"y":0.5}` in the Tiled property value. The `json:` prefix is important.

**Comment by Giwayume** [comment]
One question. If the background image is the exact width/height of the room and the anchorPoint ends up being <Infinity,Infinity>, is that going to break anything?

**Comment by parasyte** [comment]
It shouldn't become Infinity. It could become NaN due to a divide by 0, but that's why the patch in #736 has `|| 0`.

**Comment by Giwayume** [comment]
If I do 1/0 in the inspector of Chrome or Firefox I get Infinity.

**Comment by Giwayume** [comment]
http://stackoverflow.com/questions/18838301/in-javascript-why-does-zero-divided-by-zero-return-nan-but-any-other-divided-b

**Comment by parasyte** [comment]
Oh, right >_> Thanks, JavaScript.

```javascript
Math.min(x, 0) || 0;
```

**Comment by parasyte** [comment]
Fixed by 83e4ae010f90a0e21cefcbca45e6a216f1cc88a0

**Comment by Giwayume** [comment]
Do you want the parallax clouds in the platformer example or should I just toss this?

**Comment by parasyte** [comment]
I added a `platformer2` example based on this one that has parallax scrolling backgrounds.

**Pull request closed without merging**
