### PR TITLE
New UI components

### PR DESCRIPTION
**Pull request by wpernath**
Hi,

as discussed in another thread, here are two components you can use as you want:
- BaseClickableContainer: The base implementation of something clickable (inspired & copied from GUI_Object)
- BaseTextButton: A round rectangle based, hover supported, text button implementation as one implementation of BaseClickableContainer

Thanks a lot for all your help!

### CODE REVIEW

**Comment by obiot** [comment]
thinking about renaming everything as well, what about :
- UIBaseContainer 
- UISpriteContainer (former GUI_Object)
- UITextButton

what do you think ?

**Comment by wpernath** [comment]
Good idea! Let’s do it. 

Just forward thinking: what about a
- UIListView (a scrollable Container with any content?)
- UIImageTextButton
- UIcheckBox

As I am new in JavaScript etc., but I personally don’t like to use a html popup for letting the user input some text. But I don’t know how complicated it is to provide:

- UITextInput (for example to let the user input his name etc.)


Best,
  Wanja

**Comment by wpernath** [comment]
I have created a new folder in `src/renderable` named `ui` and renamed the two classes accordingly.

**Comment by obiot** [comment]
@wpernath later than never, this is finally merged and all ! thanks again for the PR.

How is your game coming along ?

**Comment by wpernath** [comment]
Good idea! Let’s do it. 

Just forward thinking: what about a
- UIListView (a scrollable Container with any content?)
- UIImageTextButton
- UIcheckBox

As I am new in JavaScript etc., but I personally don’t like to use a html popup for letting the user input some text. But I don’t know how complicated it is to provide:

- UITextInput (for example to let the user input his name etc.)


Best,
  Wanja

**Comment by obiot** [comment]
the `UITextInput` is definitely not a good idea in my opinion, as implementing a text input component that support different languages and all is a full project by itself. And then there is the whole keyboard rendering itself, that anyway is project specific, so nobody never agreed that having a base "generic" keyboard was marking sense.

we discuss this multiple time over the course of the last few years, and the conclusion was always that using css was just easier, I could not find back all the post on the topic, but here are a few of them  :
https://github.com/melonjs/melonJS/wiki/Frequently-Asked-Questions#form_inputs
https://github.com/melonjs/melonJS/issues/276
https://www.html5gamedevs.com/topic/34357-do-you-build-your-uis-in-melonjs-or-dom/#comment-197401

**Pull request merged**
