### PR TITLE
Added test execution on Chrome browser. Updated grunt, grunt plugins. Fixed new ESLint warning.

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by kibertoad** [comment]
3 tests are failing when executed on Chrome, but I'm not sure if that's not due to differences between PhantomJS and Chrome. Those can be looked at separately.

**Comment by obiot** [comment]
wow, that's great ! I was actually looking at karma the other day and was wondering if it would work as well with the travis build process (In this case Chrome is not really headless, compared to phantomJS)

**Comment by obiot** [comment]
failing tests are on:
* the ES6 Map polyfill (@see https://github.com/melonjs/melonJS/issues/810), maybe we should just remove those tests, i don't know.... 
* pointerEvent, this one should work though as they are suppossed to be supported since Chrome 55

**Comment by kibertoad** [comment]
@obiot Note the https://github.com/karma-runner/karma-chrome-launcher/pull/111 -> karma-chrome-launcher used in this PR already includes the 111, so making this CI-friendly should be a matter of just specifying a different launcher.

**Pull request merged**
