### PR TITLE
Pointer event fixes

### PR DESCRIPTION
**Pull request by agmcleod**
Tested against shapes with desktop & mobile touch simulation. Tested the multitouch with browser & iOS simulator as well.

### CODE REVIEW

**Comment by obiot** [comment]
did you also tested on window based devices (that rely on PointerEvent) ?

I guess anyway you can merge into master ? 4.0.0 is out and I already bumped the version to 4.0.1

once merged we can provide a [WIP build](http://melonjs-builds.s3.amazonaws.com/index.html?prefix=artifacts/), and see if it also fixes David's [https://groups.google.com/forum/#!topic/melonjs/Gx6sH1SN3BI](issue on the forum).

**Comment by obiot** [comment]
my god i hate that systematically avec every release, we have a major bug fix coming, ahahahah :)

**Comment by parasyte** [comment]
To be fair, we also have no test coverage for pointer events.

**Comment by obiot** [comment]
I actually thought about it a few weeks ago, but I'm not sure how to do it, although i guess we can some hackish code in the test unit that fake some pointer move ??

**Comment by parasyte** [comment]
Mocks. Events can be created with the [CustomEvents API](https://developer.mozilla.org/en-US/docs/Web/API/Event/Event) The mock can send these events to trigger any event listener.

**Comment by parasyte** [comment]
There's something of a tutorial on custom events here: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events

**Comment by agmcleod** [comment]
Not a bad idea. Also I don't really have a windows device to test it on for touch events, where the bug originally came from. I can run it on chrome though and check.

**Comment by obiot** [comment]
so we can merge this right ? or you want to add some basic pointerEvent test unit together with the PR ?

**Comment by obiot** [comment]
don't forget the CHANGELOG too :P

**Comment by obiot** [comment]
hi guys,

btw, didn't we agree we could remove support for the prefixed MS pointer event ?
https://github.com/melonjs/melonJS/blob/master/src/input/pointer.js#L130-L138
https://github.com/melonjs/melonJS/blob/master/src/input/pointer.js#L221-L222

**Comment by obiot** [comment]
yes / no ?

**Comment by obiot** [comment]
also listed here : #829

**Pull request merged**
