### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by parasyte** [comment]
@kkirsche I'm going to close this one. The version property will be used in the future. We are instead going to remove the version number from the file name in #690

**Comment by kkirsche** [comment]
From the discussions I've had it isn't going to be used and most recommendations are to use NPM. The original reason for this was for a package management site. This never happened and no one cared to make it. Personally, I think it's a waste as most discussions re future dev have been around it's slow and painful death. 

Best of luck though

**Comment by parasyte** [comment]
I'm unfamiliar with the backstory. Until it's removed from the bower docs, it doesn't hurt to keep it.

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Comment by parasyte** [comment]
Alright, I'll remove it. Thank you for the patch.

**Pull request closed without merging**
