### PR TITLE
Get typescript and jsdoc to both work

### PR DESCRIPTION
**Pull request by qpwo**

### CODE REVIEW

**Comment by qpwo** [comment]
I think I got it. Log of dist and doc:

```bash
~/g/mymelon ❯❯❯ npm run dist                                                                                     master ✱

> melonJS@10.0.0 dist /Users/l/git/mymelon
>  npm run build && npm run minify && mkdirp dist && cp -f build/*.js dist/ && npm run makedts


> melonJS@10.0.0 build
> npm run lint && rollup -c --silent


> melonJS@10.0.0 lint
> eslint --config .eslintrc.json src

Created bundle melonjs.js: 1.23 MB → 228.65 kB (gzip)
Created bundle melonjs.module.js: 1.08 MB → 215.93 kB (gzip)

> melonJS@10.0.0 minify
> terser build/melonjs.js --compress --mangle --comments  '/(?:^!|@(?:license|preserve|cc_on))/' --output build/melonjs.min.js


> melonJS@10.0.0 makedts
> npx -p typescript tsc dist/melonjs.module.js --declaration --allowJs --emitDeclarationOnly

~/g/mymelon ❯❯❯ npm run doc                                                                                      master ✱

> melonJS@10.0.0 doc /Users/l/git/mymelon
> mkdirp docs && jsdoc -c jsdoc_conf.json

~/g/mymelon ❯❯❯    
```

**Comment by obiot** [comment]
great, thanks ! I will look at it later, I'm still trying to track down a bug that is driving me crazy :)

**Comment by qpwo** [comment]
Best of luck

**Comment by obiot** [comment]
> Best of luck

a classic.... after debugging melonjs for literally hours, it turned out to be a mistake in my own example game 😵‍💫

**Pull request merged**
